### ISSUE TITLE
Exception information when crashing in setUpClass

### ISSUE THREAD

**Issue by wgemm** [mblayman/tappy#11]
Hi,
I am using tappy together with nose. In the plugin there is one thing which is not nice for debugging.
If a exception is raised in the setUpClass/tearDownClass function, the backrace shown does not show usefull information to solve the problem.

See the code below and see the difference executed with

> nosetests -s

C:\SetupTest>nosetests -s
setUp Base Class
E
======================================================================
ERROR: test suite for <class 'TestClass.Base'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\suite.py", line 209, in run
    self.setUp()
  File "C:\Python27\lib\site-packages\nose\suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "C:\Python27\lib\site-packages\nose\suite.py", line 315, in setupContext
    try_run(context, names)
  File "C:\Python27\lib\site-packages\nose\util.py", line 470, in try_run
    return func()
  File "C:\Users\gettert\Desktop\Nose\SetupTest\TestClass.py", line 14, in setUp
Class
    raise Exception("Big class setup problem")
Exception: Big class setup problem

----------------------------------------------------------------------
Ran 0 tests in 0.000s

FAILED (errors=1)

or 

> nosetests -s --with-tap 

C:\SetupTest>nosetests -s --with-tap
setUp Base Class
Traceback (most recent call last):
  File "C:\Python27\Scripts\nosetests-script.py", line 9, in <module>
    load_entry_point('nose==1.3.4', 'console_scripts', 'nosetests')()
  File "C:\Python27\lib\site-packages\nose\core.py", line 121, in __init__
    **extra_args)
  File "C:\Python27\lib\unittest\main.py", line 95, in __init__
    self.runTests()
  File "C:\Python27\lib\site-packages\nose\core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "C:\Python27\lib\site-packages\nose\core.py", line 62, in run
    test(result)
  File "C:\Python27\lib\site-packages\nose\suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "C:\Python27\lib\site-packages\nose\suite.py", line 224, in run
    test(orig)
  File "C:\Python27\lib\unittest\suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "C:\Python27\lib\site-packages\nose\suite.py", line 75, in run
    test(result)
  File "C:\Python27\lib\site-packages\nose\suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "C:\Python27\lib\site-packages\nose\suite.py", line 224, in run
    test(orig)
  File "C:\Python27\lib\site-packages\nose\suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "C:\Python27\lib\site-packages\nose\suite.py", line 214, in run
    result.addError(self, self._exc_info())
  File "C:\Python27\lib\site-packages\nose\proxy.py", line 131, in addError
    plugins.addError(self.test, err)
  File "C:\Python27\lib\site-packages\nose\plugins\manager.py", line 99, in __ca
ll__
    return self.call(*arg, **kw)
  File "C:\Python27\lib\site-packages\nose\plugins\manager.py", line 167, in sim
ple
    result = meth(*arg, **kw)
  File "C:\Python27\lib\site-packages\tap\plugin.py", line 41, in addError
    self._cls_name(test), self._description(test))
  File "C:\Python27\lib\site-packages\tap\plugin.py", line 55, in _cls_name
    return test.test.__class__.__name__
AttributeError: 'ContextSuite' object has no attribute 'test'

In the second case I get a backtrace but it does not show information which guides to the problem location.

It would be great if you could fix the problem.

See the code below to reproduce the problem.

Thanks a lot 

Wolfram

import unittest
class Base(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
	print("setUp Base Class")
        raise Exception("Big class setup problem")

    def test_1(self):
	self.assertTrue(True, "Pass everytime")

**Comment by mblayman** [comment]
@wgemm, thanks for the detailed report and reproduction steps. That is super helpful information.
